# Generated by Django 5.2.5 on 2025-09-05 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_ohlcv'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='strategy_type',
            field=models.CharField(choices=[('live', 'Live'), ('reversed', 'Reversed'), ('journaling', 'Journaling')], default='live', max_length=10),
        ),
    ]
