# Generated by Django 5.2.5 on 2025-11-09 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_position_strategy_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Liquidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('datetime', models.DateTimeField()),
                ('side', models.CharField(choices=[('LONG', 'LONG'), ('SHORT', 'SHORT')], max_length=5)),
                ('amount', models.FloatField()),
            ],
        ),
    ]
