# Generated by Django 5.2.5 on 2025-11-09 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_liquidation'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='liquidation',
            unique_together={('symbol', 'datetime', 'side')},
        ),
    ]
