# Generated by Django 5.2.5 on 2025-11-12 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_liquidation_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='liquidation',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='liquidation',
            name='interval',
            field=models.CharField(default='5min', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='liquidation',
            unique_together={('symbol', 'datetime', 'side', 'interval')},
        ),
    ]
