# Generated by Django 5.2.5 on 2025-11-12 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_liquidation_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='liquidation',
            old_name='interval',
            new_name='timeframe',
        ),
        migrations.AlterUniqueTogether(
            name='liquidation',
            unique_together={('symbol', 'datetime', 'side', 'timeframe')},
        ),
    ]
