# Generated by Django 5.2.5 on 2025-11-14 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_interval_liquidation_timeframe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='symbol',
            field=models.CharField(default='BTCUSDT', max_length=20),
        ),
        migrations.AddField(
            model_name='position',
            name='timeframe',
            field=models.CharField(choices=[('1m', '1 Minute'), ('5m', '5 Minutes'), ('15m', '15 Minutes')], default='5m', max_length=5),
        ),
    ]
