# Generated by Django 5.2.5 on 2025-11-18 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_position_symbol_position_timeframe'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='liquidation_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
