# Generated by Django 5.2.5 on 2025-12-09 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_position_liquidation_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='strategy_type',
            field=models.CharField(choices=[('live', 'Live'), ('reversed', 'Reversed')], default='live', max_length=10),
        ),
    ]
