# Generated by Django 5.2.5 on 2025-12-13 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_position_strategy_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='strategy_type',
            field=models.CharField(choices=[('live', 'Live'), ('reversed', 'Reversed'), ('journaling', 'Journaling'), ('rsi_live', 'RSI Live'), ('rsi_reversed', 'RSI Reversed')], default='live', max_length=12),
        ),
    ]
