# Generated by Django 5.2.5 on 2025-12-17 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_position_strategy_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='confirmation_candles',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
