# Generated by Django 5.2.5 on 2026-01-19 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_position_confirmation_candles'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='moving_average_50',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
