# Generated by Django 5.2.5 on 2026-01-19 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_position_moving_average_50'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='liquidation_closing_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
