# Generated by Django 5.2.5 on 2026-02-15 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_position_liquidation_closing_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='RSILiquidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('datetime', models.DateTimeField()),
                ('side', models.CharField(choices=[('LONG', 'LONG'), ('SHORT', 'SHORT')], max_length=5)),
                ('rsi', models.FloatField()),
                ('timeframe', models.CharField(default='5min', max_length=10)),
            ],
            options={
                'unique_together': {('symbol', 'datetime', 'side', 'timeframe')},
            },
        ),
    ]
