# Generated by Django 5.2.5 on 2026-02-22 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_rsiliquidation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='liquidation_closing_price',
        ),
        migrations.RemoveField(
            model_name='position',
            name='moving_average_50',
        ),
        migrations.AddField(
            model_name='position',
            name='liquidation_atr',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='liquidation_candle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='positions', to='core.ohlcv'),
        ),
        migrations.AddField(
            model_name='position',
            name='liquidation_rsi',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
